name: Build and Test
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Install dependencies
        run: mvn -DartifactId=skybot-lavalink-plugin -DgroupId=com.dunctebot -Dversion=1.6.3 -Dpackaging=jar -Dfile=deps\\skybot-lavalink-plugin-1.6.3.jar -DgeneratePom=false install:install-file
      - name: Build and Test with Maven
        run: mvn --batch-mode --update-snapshots verify
