name: Make Release
on:
  workflow_dispatch:
    inputs:
      version_number:
        description: 'Version Number'     
        required: true
        type: string
      info:
        description: 'Description of this Release'
        required: true
        type: string

jobs:
  build_jar:
    name: Build Jar
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Set Version
        uses: datamonsters/replace-action@v2
        with:
          files: 'pom.xml'
          replacements: 'Snapshot=${{ github.event.inputs.version_number }}'
      - name: Install dependencies
        run: mvn -DartifactId=skybot-lavalink-plugin -DgroupId=com.dunctebot -Dversion=1.6.3 -Dpackaging=jar -Dfile=deps\\skybot-lavalink-plugin-1.6.3.jar -DgeneratePom=false install:install-file
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      - name: Rename jar
        run: mv target/*-All.jar JaduaMusicBot-${{ github.event.inputs.version_number }}.jar
      - name: Upload jar
        uses: actions/upload-artifact@v3
        with:
          name: jar
          path: JaduaMusicBot-${{ github.event.inputs.version_number }}.jar
          if-no-files-found: error
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build_jar
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: jar
          path: .
      - name: Show Artifacts
        run: ls -R
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.inputs.version_number }}
          name: Version ${{ github.event.inputs.version_number }}
          draft: true
          prerelease: false
          artifacts: "*.jar"
          body: |
            ${{ github.event.inputs.info }}
            
            ---
            # Download: [JaduaMusicBot-${{ github.event.inputs.version_number }}.jar](https://github.com/JaduaStudios/JaduaMusicBot/releases/download/${{ github.event.inputs.version_number }}/JaduaMusicBot-${{ github.event.inputs.version_number }}.jar)
